package app.azimuthphoto.mobile.backup

import org.junit.Assert.assertEquals
import org.junit.Test
import java.io.ByteArrayInputStream

/** Vectors generated by the hub's features/sync/hashing.py — must match exactly. */
class HashingTest {
    private val data = ByteArray(25600) { (it % 256).toByte() }

    @Test
    fun contentHashMatchesHub() {
        val hash = Hashing.contentHash(ByteArrayInputStream(data), data.size.toLong())
        assertEquals("0b08ef1fa140ddccb482365a899f82f8", hash)
    }

    @Test
    fun fullHashMatchesHub() {
        val hash = Hashing.fullHash(ByteArrayInputStream(data))
        assertEquals("d7433052ecc07d0701d6983068c1ba2b", hash)
    }
}
