#!/usr/bin/env python3
"""Generate web/static/js/desktop/world_land.js from Natural Earth 110m land GeoJSON.

Projects polygons to the map's equirectangular viewBox space (1000x500,
lat clamped to +/-85), simplifies with Douglas-Peucker, drops degenerate
rings, and emits SVG path strings.
"""
import json
import math
import sys

SRC = "/tmp/ne_110m_land.geojson"
OUT = "/home/sean/Projects/pa-develop/web/static/js/desktop/world_land.js"
TOLERANCE = 1.2
MIN_POINTS = 6


def project(lng, lat):
    lat = max(-85.0, min(85.0, lat))
    x = ((lng + 180.0) / 360.0) * 1000.0
    y = ((85.0 - lat) / 170.0) * 500.0
    return (x, y)


def perp_dist(pt, a, b):
    ax, ay = a
    bx, by = b
    px, py = pt
    dx, dy = bx - ax, by - ay
    if dx == 0 and dy == 0:
        return math.hypot(px - ax, py - ay)
    return abs(dy * px - dx * py + bx * ay - by * ax) / math.hypot(dx, dy)


def rdp(points, tol):
    if len(points) < 3:
        return points
    # iterative Douglas-Peucker
    keep = [False] * len(points)
    keep[0] = keep[-1] = True
    stack = [(0, len(points) - 1)]
    while stack:
        i, j = stack.pop()
        if j <= i + 1:
            continue
        dmax, idx = -1.0, -1
        a, b = points[i], points[j]
        for k in range(i + 1, j):
            d = perp_dist(points[k], a, b)
            if d > dmax:
                dmax, idx = d, k
        if dmax > tol:
            keep[idx] = True
            stack.append((i, idx))
            stack.append((idx, j))
    return [p for p, k in zip(points, keep) if k]


def ring_to_path(ring):
    pts = [project(lng, lat) for lng, lat in ring]
    # drop closing duplicate for simplification
    if len(pts) > 1 and pts[0] == pts[-1]:
        pts = pts[:-1]
    if len(pts) < MIN_POINTS:
        return None
    # close for RDP anchoring: append first point, simplify, then strip
    simplified = rdp(pts + [pts[0]], TOLERANCE)
    if simplified and simplified[0] == simplified[-1]:
        simplified = simplified[:-1]
    if len(simplified) < MIN_POINTS:
        return None
    coords = [(round(x, 1), round(y, 1)) for x, y in simplified]
    # dedupe consecutive points after rounding
    deduped = [coords[0]]
    for c in coords[1:]:
        if c != deduped[-1]:
            deduped.append(c)
    if len(deduped) < MIN_POINTS:
        return None
    def fmt(v):
        s = f"{v:.1f}"
        return s[:-2] if s.endswith(".0") else s
    parts = [f"M {fmt(deduped[0][0])} {fmt(deduped[0][1])}"]
    parts += [f"L {fmt(x)} {fmt(y)}" for x, y in deduped[1:]]
    parts.append("Z")
    return " ".join(parts)


def main():
    with open(SRC) as f:
        gj = json.load(f)
    paths = []
    for feature in gj["features"]:
        geom = feature["geometry"]
        if geom["type"] == "Polygon":
            polys = [geom["coordinates"]]
        elif geom["type"] == "MultiPolygon":
            polys = geom["coordinates"]
        else:
            continue
        for poly in polys:
            for ring in poly:
                p = ring_to_path(ring)
                if p:
                    paths.append(p)
    body = ",\n".join("    " + json.dumps(p) for p in paths)
    out = (
        "// Generated by web/tools/gen_world_land.py from Natural Earth 110m land.\n"
        "// Equirectangular projection into the 1000x500 map viewBox (lat clamped +/-85).\n"
        "export const LAND_PATHS = [\n" + body + ",\n];\n"
    )
    with open(OUT, "w") as f:
        f.write(out)
    size = len(out.encode())
    print(f"wrote {OUT}: {len(paths)} paths, {size} bytes ({size/1024:.1f} KB)")
    if size > 92160:
        print("WARNING: over 90KB target", file=sys.stderr)


if __name__ == "__main__":
    main()
